...@config

Codebase: {
  Python Files: {
    class: [file; plural]
    Functions: {class: [function; plural]}
  }
}
Test Suite: {
  Python Files: {
    class: [file; plural]
    Test Classes: {
      class: [function; plural]
    }
  }
}
Codebase <-> Test Suite: Structural Correspondence
