direction: down

classes: {
  # Organization
  main_block: {
    style.stroke-dash: 5
    style.fill: white
  }
  # Objects
  process: {
    shape: parallelogram
  }
  check: {
    shape: diamond
  }
  person: {
    shape: person
  }
  package: {
    shape: package
  }
  file: {
    shape: page
  }
  plural: {
    style.multiple: true
  }
  codebase
  codeobj
  # Endpoints
  stop: {
    shape: circle
  }
  # Arrows
  details_for: {
    style.stroke-dash: 3
  }
  triggers: {
    style.stroke-dash: 3
    style.stroke: black
  }
}
